{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
module TestTypes where
import GHC.Generics

-- | ANON declared in own module, we need instances generated by RecordDotPreprocessor
--   but also we won't their own name pun code to interfere our tests.
data ANON = REC { a :: Int, b :: Int } deriving (Show, Generic)
